let funcsoma = require ("./funcsoma");
let funcsub = require ("./funcsub");
let funcdiv = require ("./funcdiv");
let funcmulti = require ("./funcmulti");
let contabancaria = require ("./dadosdeentrada");
console.log("------------------------------------");
console.log( funcsoma (5,10));
console.log("------------------------------------");
console.log( funcsub (4,6));
console.log("------------------------------------");
console.log( funcdiv (20,2));
console.log("------------------------------------");
console.log( funcmulti (10,4));
console.log("------------------------------------");
console.log(contabancaria.banco);